services:
  doujinshi-manager:
    image: b850108cdefg/doujin-manager:1.8
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: doujin-manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 8000:8000
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: doujin-manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysql", "-uuser", "-ppassword"]
      interval: 15s
      timeout: 10s
      retries: 10
    ports:
      - 3306:3306
